# Generated by Django 4.1.6 on 2023-02-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api_test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_radius', models.CharField(max_length=100)),
                ('mean_texture', models.CharField(max_length=100)),
                ('cancer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_test1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Api_test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.BigIntegerField()),
                ('sepal_width', models.BigIntegerField()),
                ('petal_length', models.BigIntegerField()),
                ('petal_width', models.BigIntegerField()),
                ('target', models.BigIntegerField()),
            ],
            options={
                'db_table': 'api_test2',
                'managed': False,
            },
        ),
    ]
